version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:

    pre_build:
        commands:
            - echo   "Installing dependecies"
            - npm i

    build:
        commands:
            - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist*'
